language: node_js

node_js:
  - 8

env:
  global:
    - GH_REF: github.com/shtbik/product-cart.git

before_install:
  - npm config set depth 0

before_script:
  - make build

script:
  - rm -rf .git
  - git init
  - git config user.name "Aleksandr Shtykov"
  - git config user.email "sashe4ka311@mail.ru"
  - git add ./index.html
  - git add ./CNAME
  - git add -f static
  - git add -f .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1

# safelist
branches:
  only:
  - master
